-- Auto-generated from schaetzduell-verbessert.html — 375 questions, 5 categories.
-- Regenerate with app/../scripts if the source question set changes.
insert into public.questions (cat_id, text, answer, unit, volatile) values
  (0, 'Wie oft schlägt ein Herz an einem Tag?', 100000, 'Schläge', false),
  (0, 'Wie viele Liter Blut pumpt das Herz pro Tag durch den Körper?', 7000, 'Liter', false),
  (0, 'Wie viele Kilometer Blutgefäße stecken in einem Menschen?', 100000, 'km', false),
  (0, 'Wie viele Liter Luft atmet ein Mensch pro Tag ein?', 11000, 'Liter', false),
  (0, 'Wie oft blinzelt ein Mensch an einem Tag?', 15000, 'mal', false),
  (0, 'Wie viele Kilometer läuft ein Bundesliga-Spieler pro Spiel?', 11, 'km', false),
  (0, 'Wie viele Kalorien verbrennt man bei einem Marathon?', 2700, 'kcal', false),
  (0, 'Wie viele Liter Schweiß verliert man bei einem Marathon?', 3, 'Liter', false),
  (0, 'Wie viel wiegt ein menschliches Gehirn?', 1400, 'Gramm', false),
  (0, 'Wie viele Jahre seines Lebens verschläft ein 80-Jähriger?', 26, 'Jahre', false),
  (0, 'Wie viele Kalorien stecken in einem Kilo Körperfett?', 7000, 'kcal', false),
  (0, 'Wie viele Schritte macht ein Deutscher im Schnitt pro Tag?', 5200, 'Schritte', false),
  (0, 'Wie viele Millimeter wachsen Haare pro Monat?', 12, 'Millimeter', false),
  (0, 'Wie viel Prozent des männlichen Körpers ist Wasser?', 60, 'Prozent', false),
  (0, 'Wie schnell war der schnellste je gemessene Tennis-Aufschlag?', 263, 'km/h', false),
  (0, 'Wie schnell lief Usain Bolt bei seinem 100-m-Weltrekord im Schnitt?', 37.6, 'km/h', false),
  (0, 'Wie viele Sekunden brauchte Usain Bolt für seinen 100-m-Weltrekord?', 9.58, 'Sekunden', false),
  (0, 'Wie hoch ist der Hochsprung-Weltrekord der Männer?', 245, 'Zentimeter', false),
  (0, 'Wie weit ist der Weitsprung-Weltrekord der Männer?', 895, 'Zentimeter', false),
  (0, 'Wie viele Liegestütze schafft der Weltrekordhalter in einer Stunde?', 2900, 'Liegestütze', false),
  (0, 'Wie viele Tore fallen im Schnitt pro Bundesliga-Spiel?', 3.1, 'Tore', false),
  (0, 'Wie viele Zuschauer passen ins Stadion des 1. FC Köln?', 50000, 'Zuschauer', false),
  (0, 'Wie viele Zuschauer passen ins Camp Nou in Barcelona?', 99000, 'Zuschauer', false),
  (0, 'Wie viele Menschen weltweit spielen aktiv Fußball?', 250000000, 'Menschen', false),
  (0, 'Wie viel wiegt eine olympische Langhantelstange?', 20, 'Kilogramm', false),
  (0, 'Wie viele Wochen braucht ein gebrochener Knochen zum Heilen?', 6, 'Wochen', false),
  (0, 'Wie viele Kilometer rennt ein Tennisprofi in einem Fünfsatz-Match?', 5, 'km', false),
  (0, 'Wie viele Knochen hat ein erwachsener Mensch?', 206, 'Knochen', false),
  (0, 'Wie lang ist der Dünndarm eines Erwachsenen?', 6, 'Meter', false),
  (0, 'Wie viele Nervenzellen hat das menschliche Gehirn?', 86000000000, 'Nervenzellen', false),
  (0, 'Wie viele Liter Speichel produziert ein Mensch pro Tag?', 1.5, 'Liter', false),
  (0, 'Wie viele Geschmacksknospen hat ein Mensch?', 10000, 'Knospen', false),
  (0, 'Wie viele Schweißdrüsen hat ein Mensch?', 3000000, 'Drüsen', false),
  (0, 'Wie viele Kilogramm Nahrung isst ein Mensch pro Jahr?', 500, 'Kilogramm', false),
  (0, 'Wie viele Tonnen Nahrung isst ein Mensch in seinem ganzen Leben?', 30, 'Tonnen', false),
  (0, 'Wie schnell strömt die Luft beim Niesen aus der Nase?', 160, 'km/h', false),
  (0, 'Wie viel Prozent des Sauerstoffs verbraucht allein das Gehirn?', 20, 'Prozent', false),
  (0, 'Wie viele Kalorien verbraucht das Gehirn pro Tag?', 400, 'kcal', false),
  (0, 'Wie viele Stunden braucht Essen, um den Magen zu verlassen?', 4, 'Stunden', false),
  (0, 'Wie viele Liter Urin produziert ein Mensch pro Jahr?', 550, 'Liter', false),
  (0, 'Wie viele Kilometer legt ein Handballer pro Spiel zurück?', 5, 'km', false),
  (0, 'Wie viele Kilometer fährt das Feld bei der Tour de France insgesamt?', 3400, 'km', false),
  (0, 'Wie viele Höhenmeter sammelt die Tour de France insgesamt?', 50000, 'Höhenmeter', false),
  (0, 'Wie viele Kalorien verbraucht ein Tour-de-France-Fahrer pro Tag?', 6000, 'kcal', false),
  (0, 'Wie schnell fliegt ein Ball bei einem Elfmeter?', 110, 'km/h', false),
  (0, 'Wie viele Minuten ist der Ball in einem Fußballspiel effektiv im Spiel?', 55, 'Minuten', false),
  (0, 'Wie viele Pässe spielt ein Team im Schnitt pro Bundesliga-Spiel?', 450, 'Pässe', false),
  (0, 'Wie viele Fouls gibt es im Schnitt pro Bundesliga-Spiel?', 25, 'Fouls', false),
  (0, 'Wie viele Kilometer läuft ein Schiedsrichter pro Spiel?', 11, 'km', false),
  (0, 'Wie viel wiegt ein Fußball?', 430, 'Gramm', false),
  (0, 'Wie hoch ist ein Fußballtor?', 2.44, 'Meter', false),
  (0, 'Wie breit ist ein Fußballtor?', 7.32, 'Meter', false),
  (0, 'Wie viele Grübchen hat ein Golfball?', 336, 'Grübchen', false),
  (0, 'Wie schnell ist ein Badminton-Schmetterball maximal?', 493, 'km/h', false),
  (0, 'Wie viele Kalorien hat ein Liter Bier?', 430, 'kcal', false),
  (0, 'Wie hoch ist der Grundumsatz eines erwachsenen Mannes pro Tag?', 1700, 'kcal', false),
  (0, 'Wie lange hält der Weltrekordhalter die Luft an?', 24, 'Minuten', false),
  (0, 'Wie tief geht der Freitauch-Weltrekord?', 214, 'Meter', false),
  (0, 'Wie alt wurde der älteste Mensch der Welt?', 122, 'Jahre', false),
  (0, 'Wie groß war der größte Mensch der Welt?', 272, 'Zentimeter', false),
  (0, 'Wie viel wiegt ein Neugeborenes im Schnitt?', 3400, 'Gramm', false),
  (0, 'Wie viele Knochen hat ein Neugeborenes?', 300, 'Knochen', false),
  (0, 'Wie viele Billionen Zellen hat der menschliche Körper?', 37, 'Billionen', false),
  (0, 'Wie viele Millionen rote Blutkörperchen bildet der Körper pro Sekunde?', 2.4, 'Millionen', false),
  (0, 'Wie hoch springt ein NBA-Spieler im Schnitt aus dem Stand?', 71, 'Zentimeter', false),
  (0, 'Wie viele Punkte erzielt ein NBA-Team im Schnitt pro Spiel?', 115, 'Punkte', false),
  (0, 'Wie viele Kilometer legt ein NBA-Spieler pro Spiel zurück?', 4, 'km', false),
  (0, 'Wie viele Sekunden dauert der 400-Meter-Weltrekord der Männer?', 43.03, 'Sekunden', false),
  (0, 'Wie viele Minuten braucht der Marathon-Weltrekordhalter?', 120, 'Minuten', false),
  (0, 'Wie viele Kilometer läuft der 24-Stunden-Weltrekordhalter?', 319, 'km', false),
  (0, 'Wie viel Prozent Körperfett hat ein Profifußballer?', 10, 'Prozent', false),
  (0, 'Wie viele Kalorien verbrennt eine Stunde Fußball?', 700, 'kcal', false),
  (0, 'Wie viel Gramm Protein stecken in einem Ei?', 7, 'Gramm', false),
  (0, 'Wie hoch hängt ein Volleyballnetz bei den Männern?', 243, 'Zentimeter', false),
  (0, 'Wie viele Bänder stabilisieren ein Kniegelenk?', 4, 'Bänder', false),
  (1, 'Wie viele Milliarden Bäume stehen auf der Erde?', 3000, 'Milliarden', true),
  (1, 'Wie viele Blitze schlagen weltweit pro Sekunde ein?', 100, 'Blitze', false),
  (1, 'Wie tief ist die tiefste Stelle im Marianengraben?', 10994, 'Meter', false),
  (1, 'Wie viel wiegt eine mittelgroße Schönwetterwolke?', 500, 'Tonnen', false),
  (1, 'Wie viele Inseln gehören zu Indonesien?', 17500, 'Inseln', false),
  (1, 'Wie alt kann ein Mammutbaum werden?', 3000, 'Jahre', false),
  (1, 'Wie hoch ist der höchste Baum der Welt?', 116, 'Meter', false),
  (1, 'Wie viele Kilometer fliegt eine Küstenseeschwalbe pro Jahr?', 70000, 'km', false),
  (1, 'Wie viele Eier legt eine Bienenkönigin an einem Tag?', 2000, 'Eier', false),
  (1, 'Wie viele Bienen leben im Sommer in einem Bienenstock?', 50000, 'Bienen', false),
  (1, 'Wie viele Kilometer fliegen Bienen zusammen für ein Kilo Honig?', 120000, 'km', false),
  (1, 'Wie oft schlägt das Herz einer Maus pro Minute?', 600, 'mal', false),
  (1, 'Wie viele Zähne hat ein Weißer Hai gleichzeitig im Maul?', 300, 'Zähne', false),
  (1, 'Wie lange kann ein Pottwal die Luft anhalten?', 90, 'Minuten', false),
  (1, 'Wie tief taucht ein Pottwal?', 2000, 'Meter', false),
  (1, 'Wie viel wiegt ein Straußenei?', 1400, 'Gramm', false),
  (1, 'Wie viele Insektenarten sind bisher bekannt?', 1000000, 'Arten', false),
  (1, 'Wie viel Prozent aller bekannten Tierarten sind Insekten?', 80, 'Prozent', false),
  (1, 'Wie viele Liter Wasser trinkt ein Kamel auf einmal?', 100, 'Liter', false),
  (1, 'Wie oft schlägt ein Kolibri pro Sekunde mit den Flügeln?', 50, 'mal', false),
  (1, 'Wie viele Liter Milch gibt eine Kuh pro Tag?', 25, 'Liter', false),
  (1, 'Wie schwer war der schwerste je gezüchtete Kürbis?', 1200, 'Kilogramm', false),
  (1, 'Wie hoch fliegt ein Passagierflugzeug auf Reiseflughöhe?', 11000, 'Meter', false),
  (1, 'Wie viele aktive Vulkane gibt es weltweit?', 1500, 'Vulkane', false),
  (1, 'Wie lange braucht Sonnenlicht bis zur Erde?', 8, 'Minuten', false),
  (1, 'Wie lange ist eine Elefantenkuh trächtig?', 22, 'Monate', false),
  (1, 'Wie schwer ist ein ausgewachsener Blauwal?', 150, 'Tonnen', false),
  (1, 'Wie lang ist die Chinesische Mauer insgesamt?', 21196, 'km', false),
  (1, 'Wie tief ist der Ozean im weltweiten Durchschnitt?', 3700, 'Meter', false),
  (1, 'Wie viel Prozent des Amazonas-Regenwaldes sind schon gerodet?', 17, 'Prozent', false),
  (1, 'Wie viele Liter Wasser stürzen pro Sekunde die Niagarafälle hinab?', 2400, 'Liter', false),
  (1, 'Wie hoch ist der höchste Wasserfall der Welt?', 979, 'Meter', false),
  (1, 'Wie lang ist der Erdumfang am Äquator?', 40075, 'km', false),
  (1, 'Wie viele Millionen Kilometer ist die Sonne von der Erde entfernt?', 150, 'Millionen km', false),
  (1, 'Wie heiß ist die Oberfläche der Sonne?', 5500, 'Grad Celsius', false),
  (1, 'Wie viele Milliarden Sterne hat die Milchstraße?', 200, 'Milliarden', true),
  (1, 'Wie schnell dreht sich die Erde am Äquator?', 1670, 'km/h', false),
  (1, 'Wie viele Kilometer pro Sekunde fliegt die Erde um die Sonne?', 30, 'km/s', false),
  (1, 'Wie schnell war der stärkste je gemessene Windstoß?', 408, 'km/h', false),
  (1, 'Wie viele Millimeter Regen fallen pro Jahr in Deutschland?', 790, 'Millimeter', false),
  (1, 'Wie kalt war die kälteste je gemessene Temperatur der Erde?', -89, 'Grad Celsius', false),
  (1, 'Wie heiß war die heißeste je gemessene Temperatur der Erde?', 56.7, 'Grad Celsius', false),
  (1, 'Wie hoch war die höchste je gemessene Welle?', 30, 'Meter', false),
  (1, 'Wie viel Salz steckt in einem Liter Meerwasser?', 35, 'Gramm', false),
  (1, 'Wie viele Millionen Tonnen Plastik landen pro Jahr im Meer?', 8, 'Mio. Tonnen', false),
  (1, 'Wie viele Vogelarten gibt es weltweit?', 11000, 'Arten', false),
  (1, 'Wie viele Fischarten sind bekannt?', 35000, 'Arten', false),
  (1, 'Wie viele Spinnenarten gibt es?', 50000, 'Arten', false),
  (1, 'Wie viele Ameisen leben in einem großen Ameisenhaufen?', 1000000, 'Ameisen', false),
  (1, 'Wie viele Stunden schläft eine Giraffe pro Tag?', 2, 'Stunden', false),
  (1, 'Wie viele Stunden schläft ein Koala pro Tag?', 20, 'Stunden', false),
  (1, 'Wie viele Tage kommt ein Kamel ohne Wasser aus?', 14, 'Tage', false),
  (1, 'Wie schnell schwimmt ein Schwertfisch?', 100, 'km/h', false),
  (1, 'Wie schnell ist ein Wanderfalke im Sturzflug?', 320, 'km/h', false),
  (1, 'Wie viele Millionen Geruchszellen hat eine Hundenase?', 220, 'Millionen', false),
  (1, 'Wie alt wird ein Grönlandhai?', 400, 'Jahre', false),
  (1, 'Wie viel wiegt das Herz eines Blauwals?', 180, 'Kilogramm', false),
  (1, 'Wie viele Stacheln hat ein Igel?', 8000, 'Stacheln', false),
  (1, 'Wie viele Muskeln stecken in einem Elefantenrüssel?', 40000, 'Muskeln', false),
  (1, 'Wie viele Kilogramm frisst ein Elefant pro Tag?', 150, 'Kilogramm', false),
  (1, 'Wie viele Liter Wasser trinkt ein Elefant pro Tag?', 150, 'Liter', false),
  (1, 'Wie viele Kilogramm Sauerstoff produziert ein Baum pro Jahr?', 100, 'Kilogramm', false),
  (1, 'Wie weit ist der Mond von der Erde entfernt?', 384400, 'km', false),
  (1, 'Wie viele Monde hat der Jupiter?', 95, 'Monde', false),
  (1, 'Wie viele Erdtage dauert ein Tag auf der Venus?', 243, 'Erdtage', false),
  (1, 'Wie kalt ist es im freien Weltall?', -270, 'Grad Celsius', false),
  (1, 'Wie groß ist der Durchmesser der Sonne?', 1392000, 'km', false),
  (1, 'Wie viele Erden würden in die Sonne passen?', 1300000, 'Erden', false),
  (1, 'Wie viele Tonnen Meteoritenmaterial treffen pro Tag auf die Erde?', 100, 'Tonnen', false),
  (1, 'Wie heiß ist der Erdkern?', 5200, 'Grad Celsius', false),
  (1, 'Wie viele Erdbeben werden weltweit pro Jahr registriert?', 500000, 'Erdbeben', false),
  (1, 'Wie viele Baumarten gibt es weltweit?', 73000, 'Arten', false),
  (1, 'Wie viel Prozent des Sauerstoffs produzieren die Meere?', 50, 'Prozent', false),
  (1, 'Wie viele Zentimeter wächst Bambus an einem Tag?', 90, 'Zentimeter', false),
  (1, 'Wie viele Jahre braucht eine Plastikflasche zum Zerfallen?', 450, 'Jahre', false),
  (2, 'Wie viele Reiskörner sind in einem Kilo Reis?', 50000, 'Körner', false),
  (2, 'Wie viele Kaffeebohnen braucht man für einen Espresso?', 50, 'Bohnen', false),
  (2, 'Wie viele Liter Kaffee trinkt ein Deutscher pro Jahr?', 165, 'Liter', false),
  (2, 'Wie viele Liter Bier trinkt ein Deutscher pro Jahr?', 88, 'Liter', false),
  (2, 'Wie viele Eier isst ein Deutscher pro Jahr?', 240, 'Eier', false),
  (2, 'Wie viel Fleisch isst ein Deutscher pro Jahr?', 52, 'Kilogramm', false),
  (2, 'Wie viele Kilometer fährt ein deutsches Auto pro Jahr?', 13000, 'km', false),
  (2, 'Wie viele Autos sind in Deutschland zugelassen?', 49000000, 'Autos', false),
  (2, 'Wie oft entsperrt ein Mensch sein Handy an einem Tag?', 80, 'mal', false),
  (2, 'Wie viele Minuten am Tag ist ein Deutscher am Smartphone?', 150, 'Minuten', false),
  (2, 'Wie viele Wörter spricht ein Mensch an einem Tag?', 16000, 'Wörter', false),
  (2, 'Wie viele Wörter hat ein durchschnittlicher Roman?', 80000, 'Wörter', false),
  (2, 'Wie viele Träume hat ein Mensch pro Nacht?', 5, 'Träume', false),
  (2, 'Wie oft lacht ein Kind an einem Tag?', 300, 'mal', false),
  (2, 'Wie viele Liter Wasser verbraucht eine 10-Minuten-Dusche?', 120, 'Liter', false),
  (2, 'Wie viele Liter Wasser verbraucht ein Deutscher pro Tag zu Hause?', 125, 'Liter', false),
  (2, 'Wie viele Liter Wasser stecken in einem Kilo Rindfleisch?', 15000, 'Liter', false),
  (2, 'Wie viele Liter Wasser stecken hinter einer einzigen Tasse Kaffee?', 130, 'Liter', false),
  (2, 'Wie viele Einzelteile hat ein modernes Auto?', 30000, 'Teile', false),
  (2, 'Wie viele Stufen führen im Eiffelturm bis zur Spitze?', 1665, 'Stufen', false),
  (2, 'Wie viele Stufen sind es im Kölner Dom bis zur Aussichtsplattform?', 533, 'Stufen', false),
  (2, 'Wie viele Fenster hat das Empire State Building?', 6500, 'Fenster', false),
  (2, 'Wie viele Kilometer Strich schreibt ein einzelner Bleistift?', 56, 'km', false),
  (2, 'Wie viele Legosteine werden pro Sekunde produziert?', 1100, 'Steine', false),
  (2, 'Wie oft müsste man ein Blatt Papier falten, bis es den Mond erreicht?', 42, 'mal', false),
  (2, 'Wie viele Liter passen in eine normale Badewanne?', 150, 'Liter', false),
  (2, 'Wie viele Blätter hat eine Rolle Toilettenpapier?', 200, 'Blätter', false),
  (2, 'Wie viele Milliarden Zigaretten werden in Deutschland pro Jahr geraucht?', 65, 'Milliarden', true),
  (2, 'Wie viele Minuten schaut ein Deutscher pro Tag fern?', 190, 'Minuten', false),
  (2, 'Wie viele Menschen leben in der Metropolregion Tokio?', 37000000, 'Menschen', false),
  (2, 'Wie viele Zahnbürsten verbraucht ein Mensch in seinem Leben?', 300, 'Zahnbürsten', false),
  (2, 'Wie viele Tage seines Lebens putzt ein Mensch Zähne?', 38, 'Tage', false),
  (2, 'Wie viele Mahlzeiten isst ein Mensch in seinem Leben?', 80000, 'Mahlzeiten', false),
  (2, 'Wie viele Pizzen isst ein Deutscher pro Jahr?', 12, 'Pizzen', false),
  (2, 'Wie viele Kilo Kartoffeln isst ein Deutscher pro Jahr?', 60, 'Kilogramm', false),
  (2, 'Wie viele Kilo Schokolade isst ein Deutscher pro Jahr?', 9, 'Kilogramm', false),
  (2, 'Wie viele Kilo Zucker isst ein Deutscher pro Jahr?', 33, 'Kilogramm', false),
  (2, 'Wie viele Kilo Brot isst ein Deutscher pro Jahr?', 42, 'Kilogramm', false),
  (2, 'Wie viele Liter Milch trinkt ein Deutscher pro Jahr?', 48, 'Liter', false),
  (2, 'Wie viele Liter Mineralwasser trinkt ein Deutscher pro Jahr?', 130, 'Liter', false),
  (2, 'Wie viele Bäume braucht man für eine Tonne Papier?', 14, 'Bäume', false),
  (2, 'Wie viele Kilo Papier verbraucht ein Deutscher pro Jahr?', 220, 'Kilogramm', false),
  (2, 'Wie viele Kilo Müll produziert ein Deutscher pro Jahr?', 480, 'Kilogramm', false),
  (2, 'Wie viele Kilo Verpackungsmüll produziert ein Deutscher pro Jahr?', 230, 'Kilogramm', false),
  (2, 'Wie viele Kleidungsstücke kauft ein Deutscher pro Jahr?', 60, 'Teile', false),
  (2, 'Wie viele Kleidungsstücke hängen in einem deutschen Kleiderschrank?', 95, 'Teile', false),
  (2, 'Wie viele Stunden arbeitet ein Deutscher im Schnitt pro Woche?', 35, 'Stunden', false),
  (2, 'Wie viele Krankheitstage hat ein Deutscher pro Jahr?', 15, 'Tage', false),
  (2, 'Wie viele Minuten pendelt ein Deutscher pro Tag?', 45, 'Minuten', false),
  (2, 'Wie viele Kilometer pendelt ein Deutscher pro Weg zur Arbeit?', 17, 'km', false),
  (2, 'Wie viele Fahrgäste befördert die Kölner KVB pro Tag?', 800000, 'Fahrgäste', false),
  (2, 'Wie viele Kilometer Schienennetz hat die Deutsche Bahn?', 33000, 'km', false),
  (2, 'Wie viele Kilometer Autobahn gibt es in Deutschland?', 13200, 'km', false),
  (2, 'Wie viele Brücken gibt es an deutschen Autobahnen und Bundesstraßen?', 40000, 'Brücken', false),
  (2, 'Wie viele Ampeln gibt es in Deutschland?', 100000, 'Ampeln', false),
  (2, 'Wie viele Bäckereibetriebe gibt es in Deutschland?', 9600, 'Betriebe', false),
  (2, 'Wie viele Apotheken gibt es in Deutschland?', 17000, 'Apotheken', false),
  (2, 'Wie viele Katzen leben in deutschen Haushalten?', 15700000, 'Katzen', false),
  (2, 'Wie viele Hunde leben in deutschen Haushalten?', 10500000, 'Hunde', false),
  (2, 'Wie viele Kinder werden pro Jahr in Deutschland geboren?', 690000, 'Kinder', false),
  (2, 'Wie viele Menschen werden weltweit pro Tag geboren?', 380000, 'Menschen', false),
  (2, 'Wie viele Menschen sitzen gerade gleichzeitig in einem Flugzeug?', 1000000, 'Menschen', false),
  (2, 'Wie viele Menschen leben in Köln?', 1090000, 'Menschen', false),
  (2, 'Wie viele Millionen Besucher hat der Kölner Dom pro Jahr?', 6, 'Millionen', false),
  (2, 'Wie viele Teilnehmer laufen im Kölner Rosenmontagszug mit?', 12000, 'Teilnehmer', false),
  (2, 'Wie viele Wörter passen auf eine eng beschriebene A4-Seite?', 500, 'Wörter', false),
  (2, 'Wie viele Buchstaben hat das längste Wort im Duden?', 44, 'Buchstaben', false),
  (2, 'Wie viele Kilowattstunden Strom verbraucht ein Zweipersonenhaushalt pro Jahr?', 3000, 'Kilowattstunden', false),
  (2, 'Wie viele Cent kostet eine Kilowattstunde Strom in Deutschland?', 35, 'Cent', true),
  (2, 'Wie viele Liter verbraucht ein deutsches Auto auf 100 Kilometer?', 7, 'Liter', false),
  (2, 'Wie viele Sitzplätze hat ein ICE?', 460, 'Sitzplätze', false),
  (2, 'Wie viele Millionen Passagiere fliegen pro Jahr über Köln/Bonn?', 9, 'Millionen', false),
  (2, 'Wie viele Flugzeuge sind gerade gleichzeitig in der Luft?', 10000, 'Flugzeuge', false),
  (2, 'Wie viele Millionen Erwerbstätige gibt es in Deutschland?', 46, 'Millionen', false),
  (2, 'Wie viele Betriebe hat das deutsche Handwerk?', 1000000, 'Betriebe', false),
  (3, 'Wie viele Millionen Dollar kostet ein 30-Sekunden-Spot beim Super Bowl?', 7, 'Mio. Dollar', true),
  (3, 'Wie viel verdient ein Bundesliga-Profi im Schnitt pro Jahr?', 1500000, 'Euro', true),
  (3, 'Wie hoch ist der gesetzliche Mindestlohn in Deutschland 2026?', 13.9, 'Euro', true),
  (3, 'Wie hoch ist das durchschnittliche Bruttogehalt in Deutschland pro Monat?', 4300, 'Euro', true),
  (3, 'Wie viel kostet ein Big Mac in Deutschland?', 6, 'Euro', true),
  (3, 'Wie viele Millionen Dollar kostet ein neuer Airbus A320?', 110, 'Mio. Dollar', true),
  (3, 'Wie viel wiegt ein Standard-Goldbarren aus dem Tresor?', 12.4, 'Kilogramm', false),
  (3, 'Wie viele Menschen arbeiten weltweit für Amazon?', 1500000, 'Menschen', false),
  (3, 'Wie viele Pakete stellt DHL pro Tag in Deutschland zu?', 6000000, 'Pakete', false),
  (3, 'Wie viele Milliarden Dollar Umsatz macht Apple pro Jahr?', 390, 'Milliarden', true),
  (3, 'Wie viele Millionen Euro kostet ein Formel-1-Auto?', 15, 'Mio. Euro', true),
  (3, 'Wie viel kostet ein einzelnes Formel-1-Lenkrad?', 50000, 'Euro', true),
  (3, 'Wie viele Millionen Euro brachte der teuerste Fußball-Transfer ein?', 222, 'Mio. Euro', true),
  (3, 'Wie viel kostet ein Jahr Studium an einer US-Eliteuni?', 60000, 'Dollar', true),
  (3, 'Wie viele Millionäre leben in Deutschland?', 1600000, 'Millionäre', false),
  (3, 'Wie viele Millionen Euro kostet der Bau von einem Kilometer Autobahn?', 10, 'Mio. Euro', true),
  (3, 'Wie viele Millionen Euro kostet ein ICE-Zug?', 33, 'Mio. Euro', true),
  (3, 'Wie viele Millionen Dollar kostet eine Boeing 747?', 400, 'Mio. Dollar', true),
  (3, 'Wie hoch ist die Durchschnittsmiete pro Quadratmeter in Köln?', 14, 'Euro', true),
  (3, 'Wie viel kostet eine Kugel Eis in Deutschland im Schnitt?', 1.8, 'Euro', true),
  (3, 'Wie viel kostet ein Führerschein in Deutschland?', 3000, 'Euro', true),
  (3, 'Wie viel gibt ein Deutscher pro Jahr für Lebensmittel aus?', 3000, 'Euro', true),
  (3, 'Wie hoch ist die durchschnittliche Altersrente in Deutschland pro Monat?', 1100, 'Euro', true),
  (3, 'Wie viel wiegt eine Million Euro in 500-Euro-Scheinen?', 2.3, 'Kilogramm', true),
  (3, 'Wie viele Milliarden Euro-Banknoten sind im Umlauf?', 30, 'Milliarden', true),
  (3, 'Wie viel Prozent Trinkgeld sind in Deutschland üblich?', 10, 'Prozent', false),
  (3, 'Wie viele McDonald''s-Filialen gibt es weltweit?', 40000, 'Filialen', false),
  (3, 'Wie viele IKEA-Einrichtungshäuser gibt es weltweit?', 480, 'Häuser', false),
  (3, 'In welchem Jahr wurde IKEA gegründet?', 1943, 'Jahr', false),
  (3, 'Wie viel kostet ein Liter Super-Benzin in Deutschland?', 1.75, 'Euro', true),
  (3, 'Wie viel kostet ein Kilo Safran?', 5000, 'Euro', true),
  (3, 'Wie viel kostet ein Kilo weiße Trüffel?', 4000, 'Euro', true),
  (3, 'Wie viel kostet ein Kilo Kopi Luwak, der teuerste Kaffee der Welt?', 600, 'Euro', true),
  (3, 'Wie viel kostet ein durchschnittlicher Neuwagen in Deutschland?', 45000, 'Euro', true),
  (3, 'Wie viele Millionen Euro kostet ein Bugatti Chiron?', 3, 'Mio. Euro', true),
  (3, 'Wie viel kostet ein durchschnittliches Einfamilienhaus in Deutschland?', 400000, 'Euro', true),
  (3, 'Wie viel kostet ein Quadratmeter Bauland in Deutschland im Schnitt?', 200, 'Euro', true),
  (3, 'Wie viel kostet eine Hochzeit in Deutschland im Schnitt?', 15000, 'Euro', true),
  (3, 'Wie viel kostet ein Kind bis zum 18. Geburtstag?', 150000, 'Euro', true),
  (3, 'Wie viele Milliarden Euro Schulden hat der deutsche Staat?', 2500, 'Milliarden', true),
  (3, 'Wie viele Milliarden Euro umfasst der deutsche Bundeshaushalt pro Jahr?', 480, 'Milliarden', true),
  (3, 'Wie viele Milliarden Euro gibt Deutschland pro Jahr für Verteidigung aus?', 90, 'Milliarden', true),
  (3, 'Wie viele Milliarden Euro Umsatz macht Volkswagen pro Jahr?', 320, 'Milliarden', true),
  (3, 'Wie viele Menschen arbeiten weltweit für Volkswagen?', 680000, 'Menschen', false),
  (3, 'Wie viele Millionen Autos baut VW pro Jahr?', 9, 'Millionen', false),
  (3, 'Wie viele Milliarden Dollar Umsatz macht Nike pro Jahr?', 51, 'Milliarden', true),
  (3, 'Wie viel kostet ein Paar Nike-Sneaker in der Herstellung?', 20, 'Euro', true),
  (3, 'Wie viele Dollar kostet die Herstellung eines iPhones?', 550, 'Dollar', true),
  (3, 'Wie viele Millionen Euro zahlt ein Sponsor pro Jahr für ein Bundesliga-Trikot?', 30, 'Mio. Euro', true),
  (3, 'Wie viele Millionen Euro zahlen die TV-Sender pro Saison für die Bundesliga?', 1100, 'Mio. Euro', true),
  (3, 'Wie viele Millionen Euro Prämie gibt es für den Champions-League-Sieg?', 20, 'Mio. Euro', true),
  (3, 'Wie viel kostet eine Stehplatz-Dauerkarte beim 1. FC Köln?', 200, 'Euro', true),
  (3, 'Wie viel verdient ein Bundesliga-Schiedsrichter pro Spiel?', 5000, 'Euro', true),
  (3, 'Wie viel verdient ein Erzieher in Deutschland brutto pro Monat?', 3400, 'Euro', true),
  (3, 'Wie viel verdient ein Handwerksmeister brutto pro Monat?', 4200, 'Euro', true),
  (3, 'Wie viel verdient ein Lufthansa-Pilot pro Jahr?', 150000, 'Euro', true),
  (3, 'Wie hoch ist der durchschnittliche Stundenlohn in Deutschland?', 25, 'Euro', true),
  (3, 'Wie viel kostet eine Stunde beim Anwalt?', 250, 'Euro', true),
  (3, 'Wie viel kostet ein Tag im Krankenhaus?', 800, 'Euro', true),
  (3, 'Wie viel kostet eine Kinokarte in Deutschland im Schnitt?', 10, 'Euro', true),
  (3, 'Wie viele Milliarden Euro Umsatz macht die deutsche Gastronomie pro Jahr?', 95, 'Milliarden', true),
  (3, 'Wie viel kostet ein Kölsch in einer Kölner Kneipe?', 2.3, 'Euro', true),
  (3, 'Wie viel kostet ein 30-Sekunden-Werbespot zur Primetime im deutschen TV?', 50000, 'Euro', true),
  (3, 'Wie viel verdient ein Influencer mit 100.000 Followern pro Post?', 1000, 'Euro', true),
  (3, 'Wie viel verdient ein YouTuber pro 1.000 Videoaufrufe?', 2, 'Euro', true),
  (3, 'Wie viele Milliarden Dollar Umsatz macht die Games-Branche pro Jahr?', 190, 'Milliarden', true),
  (3, 'Wie viele Milliarden Dollar Umsatz macht Netflix pro Jahr?', 39, 'Milliarden', true),
  (3, 'Wie viele Millionen Abonnenten hat Netflix weltweit?', 300, 'Millionen', true),
  (3, 'Wie viel kostet ein Quadratmeter Eigentumswohnung in München?', 9000, 'Euro', true),
  (3, 'Wie viel kostet ein Quadratmeter Eigentumswohnung in Köln?', 5000, 'Euro', true),
  (3, 'Wie viel Geld hat ein Deutscher im Schnitt auf der hohen Kante?', 30000, 'Euro', true),
  (3, 'Wie viel Bargeld trägt ein Deutscher im Portemonnaie?', 100, 'Euro', true),
  (3, 'Wie viel Prozent aller Zahlungen in Deutschland laufen bar?', 50, 'Prozent', false),
  (3, 'Wie viele Filialen hat Aldi in Deutschland?', 4200, 'Filialen', false),
  (3, 'Wie viele Menschen arbeiten bei der Deutschen Bahn?', 330000, 'Menschen', false),
  (4, 'Wie viele Stunden Video werden pro Minute auf YouTube hochgeladen?', 500, 'Stunden', false),
  (4, 'Wie viele Google-Suchen laufen pro Sekunde?', 99000, 'Suchen', false),
  (4, 'Wie viele Milliarden E-Mails werden pro Tag verschickt?', 350, 'Milliarden', true),
  (4, 'Wie viele Millionen Songs liegen auf Spotify?', 100, 'Millionen', false),
  (4, 'Wie viele Milliarden Fotos werden pro Tag hochgeladen?', 5, 'Milliarden', true),
  (4, 'Wie viele Milliarden Transistoren hat ein moderner Smartphone-Chip?', 20, 'Milliarden', true),
  (4, 'Wie viele aktive Satelliten umkreisen die Erde?', 10000, 'Satelliten', false),
  (4, 'Wie schnell fliegt die ISS um die Erde?', 28000, 'km/h', false),
  (4, 'Wie oft umrundet die ISS die Erde an einem Tag?', 16, 'mal', false),
  (4, 'Wie viele Minuten braucht ein Funksignal mindestens bis zum Mars?', 4, 'Minuten', false),
  (4, 'Wie viele Zeichen darf ein klassischer Tweet maximal haben?', 280, 'Zeichen', false),
  (4, 'Wie viele Wörter hat der erste Harry-Potter-Band?', 77000, 'Wörter', false),
  (4, 'Wie viele offizielle Emojis gibt es?', 3800, 'Emojis', false),
  (4, 'Wie viele Filme produziert Bollywood pro Jahr?', 1500, 'Filme', false),
  (4, 'Wie viele Milliarden Dollar spielte Avatar weltweit ein?', 2.9, 'Milliarden', true),
  (4, 'Wie viele Millionen Dollar kostete die Produktion von GTA 5?', 265, 'Mio. Dollar', true),
  (4, 'Wie viele Millionen Exemplare von GTA 5 wurden verkauft?', 200, 'Millionen', false),
  (4, 'Wie viele Millionen Kopien von Minecraft wurden verkauft?', 300, 'Millionen', false),
  (4, 'Wie viele Milliarden Menschen spielen weltweit Videospiele?', 3, 'Milliarden', true),
  (4, 'Wie viele Millionen Zeilen Code stecken in Windows?', 50, 'Millionen', false),
  (4, 'Wie viele Ladezyklen hält ein Smartphone-Akku durch?', 500, 'Ladezyklen', false),
  (4, 'Wie viele Menschen arbeiten weltweit für Google?', 180000, 'Menschen', false),
  (4, 'Wie viele Millionen Artikel hat die deutsche Wikipedia?', 3, 'Millionen', false),
  (4, 'Wie viele Millionen Artikel hat die englische Wikipedia?', 7, 'Millionen', false),
  (4, 'Wie viele Fotos macht ein Mensch pro Jahr mit dem Handy?', 1000, 'Fotos', false),
  (4, 'Wie viele Tasten hat eine deutsche Standardtastatur?', 105, 'Tasten', false),
  (4, 'Wie viele Sekunden dauert Bohemian Rhapsody von Queen?', 355, 'Sekunden', false),
  (4, 'Wie viele Episoden hat Game of Thrones?', 73, 'Episoden', false),
  (4, 'Wie viele Pokémon gab es in der ersten Generation?', 151, 'Pokémon', false),
  (4, 'In welchem Jahr wurde Spotify gegründet?', 2006, 'Jahr', false),
  (4, 'Wie viele Milliarden Nachrichten laufen pro Tag über WhatsApp?', 100, 'Milliarden', true),
  (4, 'Wie viele Milliarden Menschen nutzen WhatsApp?', 3, 'Milliarden', true),
  (4, 'Wie viele Milliarden Menschen nutzen Instagram?', 2, 'Milliarden', true),
  (4, 'Wie viele Milliarden Menschen nutzen TikTok?', 1.6, 'Milliarden', true),
  (4, 'Wie viele Minuten pro Tag verbringt ein Teenager mit Social Media?', 180, 'Minuten', false),
  (4, 'Wie viele Milliarden Dollar Werbeumsatz macht Google pro Jahr?', 240, 'Milliarden', true),
  (4, 'Wie viel Prozent des weltweiten Stroms verbraucht das Internet?', 2, 'Prozent', false),
  (4, 'Wie viele Millionen Bitcoin wird es maximal geben?', 21, 'Millionen', false),
  (4, 'Wie viele Terawattstunden Strom verbraucht das Bitcoin-Netzwerk pro Jahr?', 150, 'Terawattstunden', false),
  (4, 'Wie viele Kilometer Unterseekabel liegen auf dem Meeresgrund?', 1400000, 'km', false),
  (4, 'Wie viele Sprachen unterstützt Google Translate?', 130, 'Sprachen', false),
  (4, 'Wie viele Stichwörter hat der Duden?', 148000, 'Wörter', false),
  (4, 'Wie viele Wörter benutzt ein Deutscher aktiv im Alltag?', 12000, 'Wörter', false),
  (4, 'Wie viele Bücher erscheinen pro Jahr neu in Deutschland?', 70000, 'Bücher', false),
  (4, 'Wie viele Milliarden Bibeln wurden bisher verkauft?', 5, 'Milliarden', true),
  (4, 'Wie viele Millionen Harry-Potter-Bücher wurden verkauft?', 600, 'Millionen', false),
  (4, 'Wie viele Millionen Exemplare verkaufte Michael Jacksons Thriller?', 70, 'Millionen', false),
  (4, 'Wie viele Millionen Menschen sahen das WM-Finale 2014 weltweit?', 1000, 'Millionen', false),
  (4, 'Wie viele Millionen Menschen schauen in den USA den Super Bowl?', 120, 'Millionen', false),
  (4, 'Wie viele Millionen Menschen schauen den Eurovision Song Contest?', 160, 'Millionen', false),
  (4, 'Wie viele Legosteine gibt es rechnerisch pro Mensch auf der Erde?', 100, 'Steine', false),
  (4, 'Wie viele Millionen Rubik''s Cubes wurden verkauft?', 450, 'Millionen', false),
  (4, 'Wie schnell ist der Weltrekord im Lösen eines Rubik''s Cube?', 3.13, 'Sekunden', false),
  (4, 'Wie viele Züge dauert eine durchschnittliche Schachpartie?', 40, 'Züge', false),
  (4, 'Wie viele Millionen Apps gibt es im App Store?', 1.8, 'Millionen', false),
  (4, 'Wie viele Apps sind auf einem durchschnittlichen Handy installiert?', 80, 'Apps', false),
  (4, 'Wie viele Fotos liegen auf einem durchschnittlichen Smartphone?', 2000, 'Fotos', false),
  (4, 'Wie viele Kilometer Kabel stecken in einem Airbus A380?', 500, 'km', false),
  (4, 'Wie viele Millionen Einzelteile hat ein Airbus A380?', 4, 'Millionen', false),
  (4, 'Wie viele Schriftzeichen hat das chinesische Schriftsystem?', 50000, 'Zeichen', false),
  (4, 'Wie viele Bearbeitungen bekommt Wikipedia pro Minute?', 350, 'Bearbeitungen', false),
  (4, 'Wie viele Milliarden Websites gibt es weltweit?', 1.1, 'Milliarden', true),
  (4, 'Wie viele Milliarden Videos liegen auf YouTube?', 14, 'Milliarden', true),
  (4, 'Wie viele Streams braucht man auf Spotify für 1.000 Euro?', 250000, 'Streams', true),
  (4, 'Wie viele Songs erscheinen pro Tag neu auf Spotify?', 100000, 'Songs', false),
  (4, 'Wie viele Sekunden dauert ein durchschnittlicher Popsong?', 200, 'Sekunden', false),
  (4, 'Wie viele Musiker sitzen in einem großen Sinfonieorchester?', 80, 'Musiker', false),
  (4, 'Wie viele Millionen Farben kann das menschliche Auge unterscheiden?', 10, 'Millionen', false),
  (4, 'Wie viele Millionen Pixel hat ein 4K-Bild?', 8.3, 'Millionen', false),
  (4, 'Wie viele Gigabyte groß ist ein moderner AAA-Spiele-Download?', 100, 'Gigabyte', false),
  (4, 'Wie viele Länder nehmen am Eurovision Song Contest teil?', 37, 'Länder', false),
  (4, 'Wie viele Millionen Dollar spielte Avengers Endgame weltweit ein?', 2800, 'Mio. Dollar', true),
  (4, 'Wie viele Millionen Podcasts gibt es weltweit?', 4, 'Millionen', false),
  (4, 'Wie viele Museen gibt es in Deutschland?', 6800, 'Museen', false),
  (4, 'Wie viele Millionen Kinobesuche gibt es pro Jahr in Deutschland?', 90, 'Millionen', false)
on conflict (text) do nothing;
